name: Rust

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-14
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: swatinem/rust-cache@v2

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        uses: ClementTsang/cargo-action@v0.0.6
        with:
          args: --release --target ${{ matrix.target }} --verbose
          command: build

      - name: Run tests
        uses: ClementTsang/cargo-action@v0.0.6
        with:
          args: --target ${{ matrix.target }} --verbose
          command: test

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: atar-rocks-downloader-${{ matrix.os }}
          path: target/${{ matrix.target }}/release/atar-rocks-downloader*

      # Uncomment the following block if you want to send a message to Discord:
      # - name: Send message to Discord
      #   env:
      #     DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      #   uses: Ilshidur/action-discord@master
      #   with:
      #     args: 'A new commit has been pushed!
      #
      #     {{ EVENT_PAYLOAD.head_commit.url }}'